name: Call Another Workflow

on:
  push:
    branches:
      - main

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: caiofaabio/repoA
          with:
            env-params: '{"NOME": "${{ github.NOME }}", "SOBRENOME": "${{ github.SOBRENOME }}"}'