name: Call Another Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Repository Dispatch
        # uses: peter-evans/repository-dispatch@v3
        uses: caiofaabio/repoA@main
        with:
          token: "${{  secrets.TOKEN_TEST_CLASSIC }}"
      