name: Call Another Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOME: ${{ secrets.NOME }}
      SOBRENOME: ${{ secrets.SOBRENOME }}
      TOKEN: ${{ secrets.TOKEN_TEST_CLASSIC }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Repository Dispatch
        uses: caiofaabio/repoA@main
        with:
          token: '${{ env.TOKEN }}'
          repository: 'caiofaabio/repoB'
          event-type: 'workflow_dispatch'
          # client-payload: '{"NOME": "${{ env.NOME }}", "SOBRENOME": "${{ env.SOBRENOME }}"}'