name: Call Another Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOME: ${{ secrets.NOME }}
      SOBRENOME: ${{ secrets.SOBRENOME }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --production --ignore-scripts --prefer-offline

      - name: Build
        run: yarn build

      - name: Repository Dispatch
        uses: caiofaabio/repoA@main
        with:
          client-payload: |-
            {
              "NOME": "${{ env.NOME }}",
              "SOBRENOME": "${{ env.SOBRENOME }}
            }