name: Hello World

on:
  workflow_dispatch:
    inputs:
      helloWord:
        description: 'The input to the hello world script'
        required: true
        default: 'Hello World'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Hello World
        run: node helloWord.js

      