name: Hello World

on:
  workflow_dispatch:
    inputs:
      helloWord:
        description: 'The input to the hello world script'
        required: true
        default: 'Hello World'
      timestamp:
        description: 'The current timestamp'
        required: true
        default: new Date().toISOString()
      env:
        description: 'Custom env'
        required: false
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOME: ${{ secrets.NOME }}
      SOBRENOME: ${{ secrets.SOBRENOME }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Hello World
        run: node helloWord.js
      
      - name: new Date
        run: node timestamp.js

      - name: Custom Env
        run: node env.js