name: Call Another Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOME: ${{ secrets.NOME }}
      SOBRENOME: ${{ secrets.SOBRENOME }}
      TOKEN: ${{ secrets.TOKEN_TEST_CLASSIC }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        # uses: caiofaabio/repoA@main
        with:
          repository: 'caiofaabio/repoB'
          token: '${{ env.TOKEN }}'
          event-type: 'my-event'
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "NOME": "${{ env.NOME }}", "SOBRENOME": "${{ env.SOBRENOME }}"}'